### PR TITLE
Add video link for questions

### PR DESCRIPTION
**Pull request by ajayme**
Update DB:

Alter table questions add column video_link varchar(255);

### CODE REVIEW

**Comment by oqpvc** [comment]
You can (and should) alter the DB yourself: Simply add a Rails migration. They are (hopefully) automatically executed when pushing to master.

**Comment by ajayme** [comment]
Done.

**Comment by oqpvc** [comment]
:thumbsup:

**Comment by fosterfarrell9** [comment]
Great, adding the video links seems to work nicely. However it appears that the video links added to the questions do not appear when the answers are presented ( at least in my local setup).

**Comment by ajayme** [comment]
Hi. Will check later if i was able to add JavaScript to commit.

**Comment by ajayme** [comment]
Hello, all files have been added to the commit.
The label/link are not displayed in the answer presentation if the link is empty.

**Pull request merged**
