### PR TITLE
Video link bug and bug #109

### PR DESCRIPTION
**Pull request by ajayme**

### CODE REVIEW

**Comment by fosterfarrell9** [comment]
Awesome! It seems to work nicely.
Could you please still do two things:
1. Display the video links in a way  that they open in an external tab when being clicked upon (e.g. with target="_blank")
2. Please make the pull request for the "dev"-branch instead of "master". As "master" is more or less directly connected to the actual keks site, we should first merge to "dev".

**Comment by oqpvc** [comment]
Cool!

I merged it into dev.

**Comment by ajayme** [comment]
Hello,

Is there something else you want me to do?

**Comment by fosterfarrell9** [comment]
Issue #119 should be the next priority, then #113. If there is a way to implement #115, then this would be great, too. And after that, it is maybe a good idea to start the work on #106.

**Pull request merged**
